title: Web Mining
author: Nama Anda
logo: foto.JPG

repository:
  url: https://github.com/YunikaLstry/ppw  # Ganti dengan URL repositori GitHub Anda
  branch: main

execute:
  execute_notebooks: "off"

html:
  use_repository_button: true
  use_issues_button: false
  extra_css:
    - _static/custom.css

exclude_patterns:
  - "nwebmining/*"
  - ".venv/*"
  - "_build/*"
  - ".ipynb_checkpoints/*"